services:
  backend:
    build: ./backend
    image: emotion-analytics-api:v2
    restart: unless-stopped
    container_name: emotion-api
    ports:
      - "7860:7860"

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    volumes:
      - ./backend/data:/app/data

    tty: true

  frontend:
    build: ./frontend
    image: emotion-analytics-ui:v2
    restart: unless-stopped
    container_name: emotion-ui
    ports:
      - "3000:3000"

    environment:
      - NEXT_PUBLIC_WS_URL=ws://backend:7860/ws/emotion
      - NEXT_PUBLIC_API_URL=http://backend:7860

    depends_on:
      - backend